# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

PerAppConfigs:
  - App: "gst-launch-"
    Threads:
       - {"cam-server": "FOCUSED_CGROUP_IDENTIFIER"}
       - {"gst-launch-": "FOCUSED_CGROUP_IDENTIFIER"}

  - App: "cyclictest"
    Threads:
       - {"cyclictest": "FOCUSED_CGROUP_IDENTIFIER"}
    Configurations: ["0x00800001"]
