SignalConfigs:
  - SigId: "0x0001"
    Category: "0x01"
    Name: URM_APP_OPEN
    Enable: true
    Permissions: ["system", "third_party"]
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}

  - SigId: "0x0001"
    Category: "0x80"
    Name: RT_TRIGGER
    Enable: true
    Permissions: ["system", "third_party"]
    Resources:
      - {ResCode: "0x00800000", Values: [0]}
      - {ResCode: "0x00800001", Values: [0]}
      - {ResCode: "0x00800002", Values: [0]}
      - {ResCode: "0x00030003", Values: [-1]}
      - {ResCode: "0x00040003", ResInfo: "0x00000000", Values: [1]}
      - {ResCode: "0x00040004", ResInfo: "0x00000100", Values: [1]}
      - {ResCode: "0x00040005", ResInfo: "0x00000200", Values: [1]}

  - SigId: "0x0002"
    Category: "0x80"
    Name: THREAD_CONF
    Enable: true
    Permissions: ["system", "third_party"]
    Timeout: -1
    Resources:
      - {ResCode: "0x00030004", Values: ["%d", "%d", "%d", "%d", "%d", "%d", 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]}
