# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause-Clear

SignalConfigs:
  # Multimedia: category 3

  # Video decode
  # Default decode
  - SigId: "0x0001"
    Category: "0x03"
    SigType: 0
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["seraph"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_CGRP_UCLAMP_MIN", Values: [4, 0]}
      - {ResCode: "RES_CGRP_UCLAMP_MAX", Values: [4, 20]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [358]}

  # Video decode
  # Decode 5+ concurrent sessions
  - SigId: "0x0001"
    Category: "0x03"
    SigType: 5
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["seraph"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_CGRP_UCLAMP_MIN", Values: [4, 0]}
      - {ResCode: "RES_CGRP_UCLAMP_MAX", Values: [4, 20]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [358]}

  # Video decode
  # Decode 20+ concurrent sessions
  - SigId: "0x0001"
    Category: "0x03"
    SigType: 20
    Name: "URM_SIG_VIDEO_DECODE"
    Enable: true
    TargetsEnabled: ["seraph"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}

  # Camera preview
  # Default preview - 30fps
  - SigId: "0x0002"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_PREVIEW"
    Enable: true
    TargetsEnabled: ["seraph"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_CGRP_UCLAMP_MIN", Values: [4, 0]}
      - {ResCode: "RES_CGRP_UCLAMP_MAX", Values: [4, 20]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [358]}

  # Camera encode
  # Default encode - 30fps
  - SigId: "0x0003"
    Category: "0x03"
    Name: "URM_SIG_CAMERA_ENCODE"
    Enable: true
    TargetsEnabled: ["seraph"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_CGRP_UCLAMP_MIN", Values: [4, 0]}
      - {ResCode: "RES_CGRP_UCLAMP_MAX", Values: [4, 20]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [358]}

  # Camera encode multi-stream
  # encode (0-12 streams)
  - SigId: "0x0004"
    Category: "0x03"
    SigType: 0
    Name: "URM_SIG_CAMERA_ENCODE_MULTI_STREAMS"
    Enable: true
    TargetsEnabled: ["seraph"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}
      - {ResCode: "RES_CGRP_UCLAMP_MIN", Values: [4, 0]}
      - {ResCode: "RES_CGRP_UCLAMP_MAX", Values: [4, 50]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MIN", Values: [0]}
      - {ResCode: "RES_SCHED_UTIL_CLAMP_MAX", Values: [716]}

  # Camera encode multi-stream
  # encode (12+ streams)
  - SigId: "0x0004"
    Category: "0x03"
    SigType: 13
    Name: "URM_SIG_CAMERA_ENCODE_MULTI_STREAMS"
    Enable: true
    TargetsEnabled: ["seraph"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [2, 0,1,2,3]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [3, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [3, 90]}
      - {ResCode: "RES_CGRP_HIGH_MEM", Values: [3, 1048576]}
      - {ResCode: "RES_CGRP_RUN_CORES", Values: [4, 0,1,2,3,4]}
      - {ResCode: "RES_CGRP_REL_CPU_WEIGHT", Values: [4, 150]}
      - {ResCode: "RES_CGRP_CPU_LATENCY", Values: [4, -20]}
      - {ResCode: "RES_CGRP_LOW_MEM", Values: [4, 507256]}
      - {ResCode: "RES_CGRP_MIN_MEM", Values: [4, 116631]}

  # Audio Signals
  # 0x40400000: Power-collapse control, value = 0x1 = 1
  # 0x40800000: Big-cluster minimum frequency, value = 0x514 = 1300
  - SigId: "0x1200"
    Category: "0xea"
    SigType: 0
    Name: "URM_SIG_PERFLOCK_Preview"
    Enable: true
    TargetsEnabled: ["seraph"]
    Permissions: ["third_party", "system"]
    Timeout: -1
    Resources:
      - {ResCode: "RES_CPU_DMA_LATENCY", Values: [1]}
      - {ResCode: "0x008a000e", ResInfo: "0x00000000", Values:[1300]}
